[package]
name = "highlighter-core"
description = "The core library that Highlighter wraps."
license = "MIT"
homepage = "https://github.com/trimorphdev/highlighter"
repository = "https://github.com/trimorphdev/highlighter"
version = "0.1.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"