[package]
name = "highlighter-languages"
version = "0.1.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["all-languages"]
all-languages = ["brainheck"]
brainheck = []

[dependencies]
highlighter-core = { path = "../highlighter-core", version = "0.1.0-alpha" }