[package]
name = "highlighter"
version = "0.1.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["all-languages"]
all-languages = ["rust"]
rust = ["highlighter-languages/rust"]

[dependencies]
highlighter-core = { path = "../highlighter-core", version = "0.1.0-alpha" }
highlighter-languages = { path = "../highlighter-languages", version = "0.1.0-alpha", features = [] }