[package]
name = "highlighter"
description = "An extendable syntax highlighter written in Rust."
license = "MIT"
homepage = "https://github.com/trimorphdev/highlighter"
repository = "https://github.com/trimorphdev/highlighter"
readme = "../../README.md"
version = "0.1.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["all-languages", "target-html"]
all-languages = ["brainheck"]
brainheck = ["highlighter-languages/brainheck"]
target-html = ["highlighter-target-html"]

[dependencies]
highlighter-core = { path = "../highlighter-core", version = "0.1.1-alpha" }
highlighter-languages = { path = "../highlighter-languages", version = "0.1.1-alpha" }
highlighter-target-html = { path = "../highlighter-target-html", version = "0.1.1-alpha", optional = true }